version: '3.8'
services:
  bit-mentor-server:
    image: bit-mentor-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bit-mentor-server-container
    env_file:
      - .env_dev
    volumes:
      - ./.env_dev:/app/.env_dev
    ports:
      - "8000:8000"
    command: python -m server.server --env dev
    networks:
      - bit-mentor

networks:
  bit-mentor:
    external: true
