version: '3.8'
services:
  bit-mentor-server:
    image: bit-mentor-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bit-mentor-server-container
    env_file:
      - .env_dev
    volumes:
      - ./.env_dev:/app/.env_dev
      - ./logs:/app/logs   # Mount the logs directory for Logstash
    ports:
      - "8000:8000"
    command: python -m server.server --env dev
    networks:
      - bit-mentor

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # Disable security and HTTPS

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - bit-mentor

  logstash:
    image: docker.elastic.co/logstash/logstash:8.14.3
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/app/logs  # Mount the logs directory so Logstash can read the app log file
    ports:
      - "5000:5000"
    depends_on:
      - elasticsearch
    networks:
      - bit-mentor

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      #- ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - bit-mentor

networks:
  bit-mentor:
    external: true
